### ISSUE TITLE
make install_openfl_tensorflow command failed

### ISSUE THREAD

**Issue by MeiruiJiang** [IntelLabs/OpenFederatedLearning#17]
I cloned the latest version to my PC and could run 'make install_openfl' successfully.
## Question1 
But when running the next command 'make install_openfl_tensorflow', it failed.

Here is part of the **error** info:
> removing build/bdist.linux-x86_64/wheel
> we will use the wheel, and do not want the egg info
> rm -r -f openfl.tensorflow.egg-info
> venv/bin/pip install dist/openfl.tensorflow-0.0.1-py3-none-any.whl
> Processing ./dist/openfl.tensorflow-0.0.1-py3-none-any.whl
> Collecting tensorflow==1.15.2 (from openfl.tensorflow==0.0.1)
>   **Could not find a version that satisfies the requirement tensorflow==1.15.2 (from openfl.tensorflow==0.0.1) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0)**
> No matching distribution found for tensorflow==1.15.2 (from openfl.tensorflow==0.0.1)
> You are using pip version 19.0, however version 20.3.3 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> Makefile: 100: recipe for target 'venv/lib/python3/site-packages/openfl/models/tensorflow' failed
> make: *** [venv/lib/python3/site-packages/openfl/models/tensorflow] Error 1
> 

## Below is my OS information:
Linux version 5.4.0-45-generic (buildd@lcy01-amd64-014) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #49~18.04.2-Ubuntu SMP Wed Aug 26 16:29:02 UTC 2020

## Antoher question
I could succesfully run make install_openfl_pytorch. But when I ran the Federated Simulation MNIST example, I followed the steps and when intializing weights, I used '../venv/bin/python create_initial_weights_file_from_flplan.py -p pt_cnn_mnist_10.yaml -c cols_10.yaml' (cause TF couldnt installed). I also faced some error.

Below is the **error** info:
> /OpenFederatedLearning/bin$ ../venv/bin/python create_initial_weights_file_from_flplan.py -p pt_cnn_mnist_10.yaml -c cols_10.yaml
> Loaded logging configuration: logging.yaml
> Workstation openfl.flplan[18356] INFO Using FLPlan defaults for section 'network_object_init' from file '/home/anny/Documents/anny/OpenFederatedLearning/bin/federations/plans/defaults/network.yaml'
> Workstation openfl.flplan[18356] INFO After hashing /home/anny/Documents/anny/OpenFederatedLearning/bin/federations/plans/pt_cnn_mnist_10.yaml, hash is 1b65915b6858904672baafdc3d1b3c3b
> Workstation openfl.flplan[18356] INFO After hashing /home/anny/Documents/anny/OpenFederatedLearning/bin/federations/plans/defaults/network.yaml, hash is 6a79887bd08f7399f0855f1481b4b134
> Workstation openfl.flplan[18356] INFO Parsed plan:
> aggregator_object_init:
>   init_kwargs:
>     aggregator_uuid: aggregator_pt_cnn_mnist_10_6a79887b
>     best_model_fname: pytorch_cnn_best.pbuf
>     federation_uuid: pt_cnn_mnist_10_6a79887b
>     init_model_fname: pytorch_cnn_init.pbuf
>     latest_model_fname: pytorch_cnn_latest.pbuf
>     rounds_to_train: 4
> collaborator_object_init:
>   init_kwargs:
>     aggregator_uuid: aggregator_pt_cnn_mnist_10_6a79887b
>     epochs_per_round: 1.0
>     federation_uuid: pt_cnn_mnist_10_6a79887b
>     opt_treatment: RESET
>     polling_interval: 4
>     send_model_deltas: false
> data_object_init:
>   class_to_init: openfl.data.pytorch.ptmnist_inmemory.PyTorchMNISTInMemory
>   data_name_in_local_config: mnist_shard
>   init_kwargs:
>     batch_size: 256
>     channels_last: false
>     nb_collaborators: 10
> hash: 6a79887bd08f7399f0855f1481b4b134
> inference:
>   allowed: true
>   init_kwargs: {}
> model_object_init:
>   class_to_init: openfl.models.pytorch.pt_cnn.pt_cnn.PyTorchCNN
>   init_kwargs: {}
> network_object_init:
>   auto_port: true
>   cert_folder: pki
>   defaults_file: defaults/network.yaml
>   hash_salt: Anything you want. Make it unique
>   init_kwargs:
>     agg_addr: FQDN of aggregator machine
>     disable_client_auth: false
>     disable_tls: false
> 
> Traceback (most recent call last):
>   File "create_initial_weights_file_from_flplan.py", line 131, in <module>
>     main(**vars(args))
>   File "create_initial_weights_file_from_flplan.py", line 75, in main
>     data = create_data_object(flplan, collaborator_common_name, local_config, n_classes=n_classes)
>   File "/home/anny/Documents/anny/OpenFederatedLearning/venv/lib/python3.8/site-packages/openfl/flplan.py", line 246, in create_data_object
>     return create_data_object_with_explicit_data_path(flplan, data_path=data_path, **kwargs)
>   File "/home/anny/Documents/anny/OpenFederatedLearning/venv/lib/python3.8/site-packages/openfl/flplan.py", line 250, in create_data_object_with_explicit_data_path
>     return init_object(flplan['data_object_init'], data_path=data_path, **kwargs)
>   File "/home/anny/Documents/anny/OpenFederatedLearning/venv/lib/python3.8/site-packages/openfl/flplan.py", line 85, in init_object
>     return get_object(module_name, class_name, **init_kwargs)
>   File "/home/anny/Documents/anny/OpenFederatedLearning/venv/lib/python3.8/site-packages/openfl/utils.py", line 46, in get_object
>     module = importlib.import_module(module_name)
>   File "/home/anny/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/anny/Documents/anny/OpenFederatedLearning/venv/lib/python3.8/site-packages/openfl/data/pytorch/__init__.py", line 15, in <module>
>     from .ptfldata_inmemory import PyTorchFLDataInMemory
>   File "/home/anny/Documents/anny/OpenFederatedLearning/venv/lib/python3.8/site-packages/openfl/data/pytorch/ptfldata_inmemory.py", line 15, in <module>
>     import torch
> **ModuleNotFoundError: No module named 'torch'**
>  
>

**Comment by tech-alchemist** [comment]
You must have `virtualenv` (venv) activated.

#### For **Tensorflow** installation error, Try following :
```
pip install https://files.pythonhosted.org/packages/9a/d9/fd234c7bf68638423fb8e7f44af7fcfce3bcaf416b51e6d902391e47ec43/tensorflow-1.15.2-cp36-cp36m-manylinux2010_x86_64.whl
```
If following error is coming:
```
ERROR: tensorflow-1.15.2-cp36-cp36m-manylinux2010_x86_64.whl is not a supported wheel on this platform.
```
Then
- Either you must have `python 3.9` in your system
or 
- You have to update the file `setup_tensorflow.py` & change its second last line to => `install_requires=['tensorflow']`

#### For **Torch** Error (during weight creation with pytorch), Try:
```
pip install torch
pip install torchvision
```
(Will take time because torch pkg is heavier than 700 mb)
:+1:

**Comment by tech-alchemist** [comment]
You must have `virtualenv` (venv) activated.

#### For **Tensorflow** installation error, Try following :
```
pip install https://files.pythonhosted.org/packages/9a/d9/fd234c7bf68638423fb8e7f44af7fcfce3bcaf416b51e6d902391e47ec43/tensorflow-1.15.2-cp36-cp36m-manylinux2010_x86_64.whl
```
If following error is coming:
```
ERROR: tensorflow-1.15.2-cp36-cp36m-manylinux2010_x86_64.whl is not a supported wheel on this platform.
```
Then
- Either you must have `python 3.9` in your system
or 
- You have to update the file `setup_tensorflow.py` & change its second last line to => `install_requires=['tensorflow']`

#### For **Torch** Error (during weight creation with pytorch), Try:
```
pip install torch
pip install torchvision
```
> Will take time because torch pkg is heavier than 700 mb)

All the best... :+1:

**Comment by alexkarargyris** [comment]
@tech-alchemist Thanks for sharing this workaround. I tried the second option `install_requires=['tensorflow']` and it installs version 2.4.1 but when running I get the following error:
`
Traceback (most recent call last):
  File "create_initial_weights_file_from_flplan.py", line 131, in <module>
    main(**vars(args))
  File "create_initial_weights_file_from_flplan.py", line 81, in main
    wrapped_model = create_model_object(flplan, data, model_device=model_device)
  File "/Users/alexandroskarargyris/Downloads/OpenFederatedLearning/venv/lib/python3.8/site-packages/openfl/flplan.py", line 97, in create_model_object
    return init_object(flplan['model_object_init'], data=data_object, device=model_device)
  File "/Users/alexandroskarargyris/Downloads/OpenFederatedLearning/venv/lib/python3.8/site-packages/openfl/flplan.py", line 85, in init_object
    return get_object(module_name, class_name, **init_kwargs)
  File "/Users/alexandroskarargyris/Downloads/OpenFederatedLearning/venv/lib/python3.8/site-packages/openfl/utils.py", line 47, in get_object
    return module.__getattribute__(class_name)(**kwargs)
  File "/Users/alexandroskarargyris/Downloads/OpenFederatedLearning/venv/lib/python3.8/site-packages/openfl/models/tensorflow/keras_cnn/keras_cnn.py", line 34, in __init__
    super().__init__(**kwargs)
  File "/Users/alexandroskarargyris/Downloads/OpenFederatedLearning/venv/lib/python3.8/site-packages/openfl/models/tensorflow/kerasflmodel.py", line 43, in __init__
    config = tf.ConfigProto(intra_op_parallelism_threads=NUM_PARALLEL_EXEC_UNITS,
AttributeError: module 'tensorflow' has no attribute 'ConfigProto'
`

I think the reason is that OpenFL uses a lower version of TF.

**Comment by msheller** [comment]
@tech-alchemist , @MeiruiJiang, @alexkarargyris ,

Open Federated Learning has moved to https://github.com/intel/openfl

The project has graduated to a fully-supported project with a production team! That version supports TF2.
